### ISSUE TITLE
备份文件为空压缩文件

### ISSUE THREAD

**Issue by M3DaLou** [Purple-CSGO/CSGO-Toolbox-Qt#21]
备份出来的文件是空的压缩包，路径都正确也都能获取到个人资料文件夹但是备份出来的文件是空的压缩包

**Comment by Purple-CSGO** [comment]
麻烦给个人CFG文件夹、工具箱第一个页面和空压缩包的位置截图

**Comment by M3DaLou** [comment]
![J0(F@3%$Q1N3SO2W)Q%B350](https://user-images.githubusercontent.com/43593321/73957086-d0eaba00-4940-11ea-9ce2-fb23175f564a.png)
![DNK3RDSG@04HWABRXO~QB~U](https://user-images.githubusercontent.com/43593321/73957129-e1029980-4940-11ea-9abf-bb9dd35bcbc1.png)
![WB5ZU0})CXV2@Q9A(RHX}RA](https://user-images.githubusercontent.com/43593321/73957150-e9f36b00-4940-11ea-9523-ff39ed4a4942.png)
![APFQ8OPCY5 JINE%@9YJQU9](https://user-images.githubusercontent.com/43593321/73957201-00012b80-4941-11ea-9906-3fc4e4851be8.png)

**Comment by M3DaLou** [comment]
![image](https://user-images.githubusercontent.com/43593321/73957321-2626cb80-4941-11ea-8925-7cca6aa16491.png)
就第一个id不知道为啥是这样的

**Comment by Purple-CSGO** [comment]
这是id没获取好的原因，可以发一下你的64位id和对应的(一般)9位数字id吗？userdata目录下的文件夹名称就是id。

麻烦等待后续版本改进吧，这段时间很忙

**Comment by M3DaLou** [comment]
360994882

**Comment by Purple-CSGO** [comment]
问题已解决，见v1.0.3版本
