### ISSUE TITLE
打开主程序，闪退，无报错

### ISSUE THREAD

**Issue by DFOUD** [Purple-CSGO/CSGO-Toolbox-Qt#23]
打开主程序后有启动图，但是5秒后消失，无法启动
以下是Windows事件的信息
错误应用程序名称: CSGO工具箱.exe，版本: 1.0.3.0，时间戳: 0x5e451717
错误模块名称: CSGO工具箱.exe，版本: 1.0.3.0，时间戳: 0x5e451717
异常代码: 0xc0000005
错误偏移量: 0x00000000007561fd
错误进程 ID: 0x39b4
错误应用程序启动时间: 0x01d5e3f4f76aa7d1
错误应用程序路径: D:\Users\dfoud\Desktop\CSGO-Toolbox.1.0.3 (1)\CSGO工具箱.exe
错误模块路径: D:\Users\dfoud\Desktop\CSGO-Toolbox.1.0.3 (1)\CSGO工具箱.exe
报告 ID: 57fb4d3d-6236-408f-bb9b-5bb46ad1d44a
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by Purple-CSGO** [comment]
尝试放在其他位置，直接放在桌面可能有问题。

方便提供一下其他的信息吗？比如系统版本，部分硬件信息，csgo和steam的位置

**Comment by DFOUD** [comment]
已经更换过应用位置，系统是微软官网下载的1909最新版系统，cpu是r5 3600x，显卡是1060，csgo与steam放在C盘默认位置

**Comment by Purple-CSGO** [comment]
电脑里是不是有Windows Defender或360等软件，看看是不是有文件被隔离了，我用UPX压缩了exe和dll的文件大小，有的地方会误报，检查之后重新下载解压安装包可能有用

**Comment by DFOUD** [comment]
没有安装任何第三方杀毒软件，仅仅使用了WD，但也将所有硬盘分区目录设为排除

**Comment by FXXKYOUMAMA** [comment]
我也出现了这个问题，同样是只用了WD，换了位置。但还是闪退

**Comment by DFOUD** [comment]
问题解决了，我重装了Windows系统，直接在系统内点击setup.exe更新，保留所有文件

**Comment by DFOUD** [comment]
问题没有解决，第二次打开依旧闪退

**Comment by Purple-CSGO** [comment]
。。。。那咋办嘛

**Comment by Evyde** [comment]
莫非是目录中文名的问题？

**Comment by jackieyiwu** [comment]
我也是闪退 3600X CPU 另一台电脑就可以
