### ISSUE TITLE
[Feature Request]建议增加配置文件自定义、常用参数选择功能

### ISSUE THREAD

**Issue by Evyde** [Purple-CSGO/CSGO-Toolbox-Qt#25]
比如有一些单人训练投掷物的指令，如mp_xxxx等，还有诸如`bind v "toggle cl_righthand 0 1"`等常用指令，这些可以由用户自由选择，然后写入到cfg文件当中，并完成对原有cfg文件的自动备份和覆盖。

**Comment by Purple-CSGO** [comment]
这个考虑过，做Config Editor，但是难度较高，后面再说
