### ISSUE TITLE
请问还会更新新版本吗

### ISSUE THREAD

**Issue by Entropy-Xu** [Purple-CSGO/CSGO-Toolbox-Qt#27]
请问还会更新新版本吗？当前版本在最新的windows11上已经无法启动了。

**Comment by Purple-CSGO** [comment]
新版工具箱正在开发中，基础功能已经实现，因为考虑到付费增值服务，有些安全的机制需要实现，大概5月下旬或者6月上旬开始公测，公测开始后会在这个仓库发布：https://github.com/One-Studio/CSGO-Toolbox-Public

另外旧版我用最新的win11是可以启动的，可能是缺少什么库吧
