### ISSUE TITLE
转换Demo分享链接为真实的下载链接URL

### ISSUE THREAD

**Issue by Purple-CSGO** [Purple-CSGO/CSGO-Toolbox-Qt#4]
目前难点在使用封装源代码封装成DLL库，再封装一层CLR 标准C++库，最后在QT C++中调用，调用成功时功能完成

**Comment by maojiuyuqi** [comment]
你好，我想问一下这个问题你最后怎么解决的吗，我现在qt可以调用源代码了，但是依赖库的版本点问题，导致源代码执行报错
